GET http://localhost:8000/api/v1


# ==========Admin API
###POST NEW ADMIN USER
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"Dipu",
    "lName":"Dangol",
    "email":"d@ad.com",
    "password":"123456",
    "confirmPassword":"123456",
    "phone":"1234567789",
    "address":"sydney",
    "dob":"2020-8-18"
}


### http://localhost:3000/admin/verifyemail?c=sasas&e=asasas



### admin user, login 
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    "email":"aass@d.com",
     "password":"123456"

}
