GET http://localhost:8000/api/v1


# ==========Admin API
###POST NEW ADMIN USER
POST http://localhost:8000/api/v1/admin-user
Content-Type: application/json

{
    "fName":"Dipu",
    "lName":"Dangol",
    "email":"d@ad.com",
    "password":"123456",
    "confirmPassword":"123456",
    "phone":"1234567789",
    "address":"sydney",
    "dob":"2020-8-18"
}


### http://localhost:3000/admin/verifyemail?c=sasas&e=asasas



### admin user, login 
POST http://localhost:8000/api/v1/admin-user/login
Content-Type: application/json

{
    "email":"a@ddd.com",
     "password":"123456"

}


###====categories apis
POST http://localhost:8000/api/v1/category
Content-Type: application/json

{
    "status":"active",
    "name":"macs macbook",
    "parentId":"63053099f4d3a3cd3f8539c5"

}

###get categoies

GET http://localhost:8000/api/v1/category/630530e2f4d3a3cd3f8539c9